from __future__ import annotations

import json
import math
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk


class RegionalComparisonApp(tk.Toplevel):
    AXES = [
        ("environment", "環境性能"),
        ("resilience", "災害適応性"),
        ("climate_fit", "気候適合性"),
        ("durability", "耐久性"),
        ("local_availability", "材料・施工性"),
        ("legal_readiness", "法規確認度"),
        ("data_confidence", "データ信頼度"),
    ]

    def __init__(
        self,
        master,
        root_dir: Path,
        language="ja",
        project_context=None,
    ):
        super().__init__(master)
        self.language = language
        self.project_context = project_context
        self.results = []
        self.title(
            "地域別CO₂・エネルギー・適合性比較"
            if language == "ja"
            else "Regional CO₂, Energy and Suitability Comparison"
        )
        self.geometry("1420x840")
        self.build()
        self.load_generated_projects()

    def t(self, ja, en):
        return ja if self.language == "ja" else en

    def build(self):
        top = ttk.Frame(self)
        top.pack(fill="x", padx=10, pady=5)
        ttk.Button(
            top,
            text=self.t(
                "地域別Project JSONを読込・比較開始",
                "Load Regional Project JSONs and Start Comparison",
            ),
            command=self.load_generated_projects,
        ).pack(side="right")

        self.folder_var = tk.StringVar(value="")
        ttk.Label(
            top,
            text=self.t("読込元：", "Source folder:"),
        ).pack(side="left")
        ttk.Label(
            top,
            textvariable=self.folder_var,
            foreground="#444444",
            wraplength=800,
        ).pack(side="left", padx=5)

        ttk.Label(
            self,
            text=self.t(
                "Module 9が基本Project JSONと同じフォルダーへ生成した独立Project JSONを読み込み、"
                "同一工法の地域別結果を比較します。",
                "Loads the independent regional Project JSON files generated by Module 9 "
                "in the same folder as the base Project JSON.",
            ),
            foreground="#8b0000",
            wraplength=1360,
        ).pack(fill="x", padx=12, pady=5)

        pane = ttk.Panedwindow(self, orient="horizontal")
        pane.pack(fill="both", expand=True, padx=10, pady=5)
        left = ttk.Frame(pane)
        right = ttk.Frame(pane)
        pane.add(left, weight=4)
        pane.add(right, weight=3)

        columns = (
            "city", "file", "score", "recommendation",
            "environment", "resilience", "climate",
            "durability", "availability", "legal", "confidence",
        )
        self.tree = ttk.Treeview(
            left,
            columns=columns,
            show="headings",
        )
        headings = [
            self.t("地域", "Region"),
            self.t("JSON", "JSON"),
            self.t("総合点", "Score"),
            self.t("判定", "Status"),
            self.t("環境", "Environment"),
            self.t("災害", "Resilience"),
            self.t("気候", "Climate"),
            self.t("耐久", "Durability"),
            self.t("材料施工", "Availability"),
            self.t("法規", "Legal"),
            self.t("信頼度", "Confidence"),
        ]
        widths = [140, 260, 70, 115, 65, 65, 65, 65, 80, 65, 70]
        for key, label, width in zip(columns, headings, widths):
            self.tree.heading(key, text=label)
            self.tree.column(key, width=width, anchor="center")
        self.tree.pack(fill="both", expand=True)
        self.tree.bind("<<TreeviewSelect>>", self.draw_selected)

        self.canvas = tk.Canvas(
            right,
            width=560,
            height=560,
            bg="white",
        )
        self.canvas.pack(fill="both", expand=True)
        self.detail = tk.Text(right, height=11, wrap="word")
        self.detail.pack(fill="x")

    def _regional_files(self, base_project):
        regional = base_project.get("regional_analysis") or {}
        entries = regional.get("generated_region_files") or []
        base_folder = Path(self.project_context.path).parent
        files = []
        for entry in entries:
            path = Path(entry.get("path") or "")
            if not path.is_absolute():
                path = base_folder / (entry.get("file") or path.name)
            if path.exists():
                files.append((entry, path))
        return files

    def load_generated_projects(self):
        for item in self.tree.get_children():
            self.tree.delete(item)
        self.results = []

        if self.project_context is None or self.project_context.path is None:
            return

        base_project = self.project_context.reload()
        base_folder = Path(self.project_context.path).parent
        self.folder_var.set(str(base_folder))

        regional_files = self._regional_files(base_project)
        if not regional_files:
            messagebox.showwarning(
                self.title(),
                self.t(
                    "Module 9で地域別Project JSONを生成してください。",
                    "Generate regional Project JSON files in Module 9 first.",
                ),
                parent=self,
            )
            return

        for entry, path in regional_files:
            try:
                project = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                continue

            result = (
                project.get("regional_analysis", {})
                .get("current_region_result", {})
            )
            if not result:
                continue
            axes = result.get("axes") or {}
            city = (
                project.get("common", {}).get("city")
                or entry.get("city")
                or path.stem
            )
            item_id = self.tree.insert(
                "",
                "end",
                values=(
                    city,
                    path.name,
                    result.get("overall_score", "-"),
                    result.get("recommendation", "-"),
                    axes.get("environment", "-"),
                    axes.get("resilience", "-"),
                    axes.get("climate_fit", "-"),
                    axes.get("durability", "-"),
                    axes.get("local_availability", "-"),
                    axes.get("legal_readiness", "-"),
                    axes.get("data_confidence", "-"),
                ),
            )
            self.results.append(
                (item_id, result, city, path, project)
            )

        if self.results:
            self.tree.selection_set(self.results[0][0])
            self.draw_selected()

    def draw_selected(self, event=None):
        selected = self.tree.selection()
        if not selected:
            return
        found = next(
            (item for item in self.results if item[0] == selected[0]),
            None,
        )
        if not found:
            return

        _, result, city, path, project = found
        self.draw_radar(result.get("axes") or {}, city)

        derivation = project.get("regional_derivation") or {}
        batch = project.get("batch_location_analysis") or {}
        location_analysis = batch.get("location_analysis") or {}
        common = project.get("common") or {}

        lines = [
            f'{self.t("地域", "Region")}：{city}',
            f'JSON：{path}',
            f'{self.t("総合点", "Score")}：{result.get("overall_score", "-")}',
            f'{self.t("判定", "Status")}：{result.get("recommendation", "-")}',
            f'{self.t("国", "Country")}：{common.get("country", "")}',
            f'{self.t("緯度・経度", "Latitude / Longitude")}：'
            f'{common.get("latitude", "")}, {common.get("longitude", "")}',
            f'{self.t("年間暖房エネルギー概算", "Estimated annual heating energy")}：'
            f'{location_analysis.get("estimated_annual_heating_energy_kWh", "-")} kWh',
            f'{self.t("年間冷房エネルギー概算", "Estimated annual cooling energy")}：'
            f'{location_analysis.get("estimated_annual_cooling_energy_kWh", "-")} kWh',
            f'{self.t("年間PV発電量概算", "Estimated annual PV generation")}：'
            f'{location_analysis.get("estimated_annual_pv_generation_kWh", "-")} kWh',
            f'{self.t("条件・注意", "Conditions / notes")}：'
            f'{", ".join(result.get("blockers") or [self.t("なし", "None")])}',
            "",
            derivation.get("notice_ja", "")
            if self.language == "ja"
            else (
                "This is an independent regional Project JSON. "
                "Planning estimates require verification with local data."
            ),
        ]

        self.detail.delete("1.0", "end")
        self.detail.insert("1.0", "\n".join(lines))

    def draw_radar(self, axes, title):
        canvas = self.canvas
        canvas.delete("all")
        width = max(canvas.winfo_width(), 560)
        height = max(canvas.winfo_height(), 560)
        center_x = width / 2
        center_y = height / 2
        radius = min(width, height) * 0.34
        count = len(self.AXES)

        for level in range(1, 6):
            points = []
            current_radius = radius * level / 5
            for index in range(count):
                angle = -math.pi / 2 + 2 * math.pi * index / count
                points.extend([
                    center_x + current_radius * math.cos(angle),
                    center_y + current_radius * math.sin(angle),
                ])
            canvas.create_polygon(
                points,
                outline="#bbbbbb",
                fill="",
            )

        data_points = []
        for index, (key, label_ja) in enumerate(self.AXES):
            angle = -math.pi / 2 + 2 * math.pi * index / count
            canvas.create_line(
                center_x,
                center_y,
                center_x + radius * math.cos(angle),
                center_y + radius * math.sin(angle),
                fill="#cccccc",
            )
            label = label_ja
            canvas.create_text(
                center_x + (radius + 32) * math.cos(angle),
                center_y + (radius + 32) * math.sin(angle),
                text=label,
                width=90,
            )
            current_radius = radius * float(axes.get(key, 0)) / 100
            data_points.extend([
                center_x + current_radius * math.cos(angle),
                center_y + current_radius * math.sin(angle),
            ])

        canvas.create_polygon(
            data_points,
            outline="#333333",
            fill="#dddddd",
            stipple="gray50",
            width=2,
        )
        canvas.create_text(
            center_x,
            24,
            text=title,
            font=("Yu Gothic UI", 16, "bold"),
        )
